controllers:
    resource: ../src/Controller/
    type: attribute

website_index:
    path: /
    controller : App\Controller\WebsiteController::index

user_login:
    path: /login
    controller: App\Controller\AuthController::index


user_register:
    path: /register
    controller: App\Controller\UserController::register