controllers:
    resource: ../src/Controller/
    type: attribute

website_index:
    path: /
    controller : App\Controller\WebsiteController::index

user_login:
    path: /index.php/login
    controller: App\Controller\AuthController::login

user_logout:
    path: /index.php/logout
    controller: App\Controller\AuthController::logout

user_register:
    path: /index.php/register
    controller: App\Controller\UserController::register
